name: Deploy

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker compose up
        run: |
          cd dev
          docker compose -f docker-compose-dev.yml up -d

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker compose up
        run: |
          cd prod
          docker compose -f docker-compose-prod.yml up -d
